// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/expense" | "/inventory" | "/inventory/add" | "/parties" | "/pos" | "/production" | "/purchase/bills" | "/purchase/bills/create" | "/purchase/payments" | "/purchase/returns" | "/sales/invoices" | "/sales/invoices/create" | "/sales/payments" | "/sales/returns" | "/transfer"
type PageRoutes = never
type LayoutRoutes = "/" | "/expense" | "/inventory" | "/purchase" | "/sales"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/dashboard": {}
  "/expense": {}
  "/inventory": {}
  "/inventory/add": {}
  "/parties": {}
  "/pos": {}
  "/production": {}
  "/purchase": {}
  "/purchase/bills": {}
  "/purchase/bills/create": {}
  "/purchase/payments": {}
  "/purchase/returns": {}
  "/sales": {}
  "/sales/invoices": {}
  "/sales/invoices/create": {}
  "/sales/payments": {}
  "/sales/returns": {}
  "/transfer": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/expense": never
  "/inventory": never
  "/purchase": never
  "/sales": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
