// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/expense/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expense">> = Specific
  const handler = {} as typeof import("../../../src/app/expense/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/add">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/parties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parties">> = Specific
  const handler = {} as typeof import("../../../src/app/parties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos">> = Specific
  const handler = {} as typeof import("../../../src/app/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/production/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production">> = Specific
  const handler = {} as typeof import("../../../src/app/production/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/purchase/bills/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/bills/create">> = Specific
  const handler = {} as typeof import("../../../src/app/purchase/bills/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/purchase/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/bills">> = Specific
  const handler = {} as typeof import("../../../src/app/purchase/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/purchase/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/purchase/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/purchase/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/returns">> = Specific
  const handler = {} as typeof import("../../../src/app/purchase/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sales/invoices/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/invoices/create">> = Specific
  const handler = {} as typeof import("../../../src/app/sales/invoices/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sales/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/invoices">> = Specific
  const handler = {} as typeof import("../../../src/app/sales/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sales/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/sales/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sales/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/returns">> = Specific
  const handler = {} as typeof import("../../../src/app/sales/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfer">> = Specific
  const handler = {} as typeof import("../../../src/app/transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/expense/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/expense">> = Specific
  const handler = {} as typeof import("../../../src/app/expense/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/purchase/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/purchase">> = Specific
  const handler = {} as typeof import("../../../src/app/purchase/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sales/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sales">> = Specific
  const handler = {} as typeof import("../../../src/app/sales/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
